### ISSUE TITLE
Missing map icons

### ISSUE THREAD

**Issue by fank** [FridayNightFight/OCAP#8]
- ~~`loc_Fuelstation`~~
- `flag_CSAT`
- `flag_NATO`

**Comment by fank** [comment]
Looks like loc_Fuelstation exists, only the flags are missing

**Comment by indig0fox** [comment]
added 000000.png matching image of existing FFFFFF.png for any markers that didn't already have one, namely all factions and flags, in 3f8cacd2a15d52c37b09e3ce49e354edf87ad981
